### ISSUE TITLE
Не выполняются скрипты schema.sql и data.sql

### ISSUE THREAD

**Issue by jnglman** [pauzholis/BookShelf#1]
Пытаюсь запустить ваш проект командой `mvn spring-boot:run`, при этом наполнения бд не происходит. Нужно ли указывать какие-то дополнительные параметры?

**Comment by pauzholis** [comment]
Временное решение: надо положить схемы в ресурсы на первый запуск.

**Comment by pauzholis** [comment]
В будущем, возможно, прикрутим flyWay или liquibase, а пока так. Вся информация в README.
